### ISSUE TITLE
Не отрисовывается секция на странице Ядро(core)

### ISSUE THREAD

**Issue by eugenekogan-spb** [fhir-ru/zendoc#19]
На странице http://fhir-ru.zendoc.me/core в самом конце я добавил секцию

:feedback md/
Есть предложения по улучшению этой страницы? Пиши сюда [[d 94]].

Она не отрисовывается.

**Comment by Semalexa** [comment]
Поправила. Был лишний пробел перед ключом :feedback md/

https://github.com/fhir-ru/zendoc/commit/b2892f80edb4f8c1b5d7f6bb0f12de72148d18fe
